In [1]:
import numpy as np

In [4]:
l = list(range(10))
arr = np.array(l)
print(arr)
print(type(arr))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [5]:
print(arr.shape)

(10,)


In [23]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l3 = [9,10,11,12]
arr = np.array([l1,l2,l3])
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [29]:
arr = arr.reshape(2,6)
print(arr)
print(arr.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


# Indexing

In [43]:
arr = np.array(list(range(1,26)))
print(arr[3])

4


In [47]:
arr = arr.reshape(5,5)
print(arr)
print(arr[0:2,0:2])
print(arr[:2,2:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[1 2]
 [6 7]]
[[3 4]
 [8 9]]


In [48]:
a = np.arange(1,11,2)
print(a)

[1 3 5 7 9]


In [51]:
a = np.linspace(1,10,20)
print(a)
print(len(a))

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]
20


# Copy function and broadcasting

In [52]:
a[5:] = 100
print(a)

[  1.           1.47368421   1.94736842   2.42105263   2.89473684
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.
 100.         100.         100.         100.         100.        ]


In [53]:
a1 = a

In [54]:
a1[5:] = 500
print(a1)
print(a)

[  1.           1.47368421   1.94736842   2.42105263   2.89473684
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.        ]
[  1.           1.47368421   1.94736842   2.42105263   2.89473684
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.        ]


In [55]:
a1 = a.copy()
a1[5:] = 300
print(a1)
print(a)

[  1.           1.47368421   1.94736842   2.42105263   2.89473684
 300.         300.         300.         300.         300.
 300.         300.         300.         300.         300.
 300.         300.         300.         300.         300.        ]
[  1.           1.47368421   1.94736842   2.42105263   2.89473684
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.        ]


In [61]:
val = 2
print(a<2)
print(a*2)
print(a/2)
print(a[a>val])

[ True  True  True False False False False False False False False False
 False False False False False False False False]
[   2.            2.94736842    3.89473684    4.84210526    5.78947368
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000.         1000.         1000.
 1000.         1000.         1000.         1000.         1000.        ]
[  0.5          0.73684211   0.97368421   1.21052632   1.44736842
 250.         250.         250.         250.         250.
 250.         250.         250.         250.         250.
 250.         250.         250.         250.         250.        ]
[  2.42105263   2.89473684 500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.         500.         500.         500.
 500.         500.        ]


In [63]:
print(np.ones(4,dtype=int))
print(np.ones((2,5)))

[1 1 1 1]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
print(np.random.rand(3,3))

[[0.1956777  0.73632169 0.40901427]
 [0.51776998 0.89222161 0.88936603]
 [0.23755856 0.00979617 0.38800123]]


In [65]:
print(np.random.randn(4,4))

[[ 2.1736962  -0.1122981   0.50495776 -0.53822065]
 [ 0.42043402 -0.43117937 -0.7011503   1.02717703]
 [-0.26527714 -0.182967    0.3218756  -0.12594596]
 [ 0.87811922 -0.19952945  0.98483664  1.10038426]]


In [68]:
print(np.random.randint(0,100,10).reshape(2,5))

[[31 99 46 62 23]
 [44 76 63  0 58]]


In [70]:
print(np.random.random_sample())

0.4634783735900794
