In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.arange(20).reshape(5,4), 
                  index=['Row1','Row2','Row3','Row4','Row5'],
                 columns=['Column1','Column2','Column3','Column4'])

In [3]:
df.head()

Column1  Column2  Column3  Column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [4]:
df.to_csv('test.csv')

In [7]:
# loc - row index
# iloc - both row and col index
print(df.loc['Row1'])
print(type(df.loc['Row1']))
#Series - one column or one data
#Dataframe - more than one col and one row

Column1    0
Column2    1
Column3    2
Column4    3
Name: Row1, dtype: int64
<class 'pandas.core.series.Series'>


In [8]:
print(df.iloc[:2,:2])
print(type(df.iloc[:2,:2]))

      Column1  Column2
Row1        0        1
Row2        4        5
<class 'pandas.core.frame.DataFrame'>


In [13]:
print(df.iloc[:2,:1])
print(type(df.iloc[:2,:1]))
#Anything in 2-d index -> dataframe
print(type(df.iloc[:1,:1]))
#Because there are two rows

      Column1
Row1        0
Row2        4
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


In [14]:
print(df.iloc[:,0])
print(type(df.iloc[:,0]))
#Now its series

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64
<class 'pandas.core.series.Series'>


In [15]:
df.iloc[:,1:]

Column2  Column3  Column4
Row1        1        2        3
Row2        5        6        7
Row3        9       10       11
Row4       13       14       15
Row5       17       18       19

In [18]:
#Converting dataframes to arrays - .values
print(df.iloc[:,1:].values)
print(df.iloc[:,1:].values.shape)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]
 [17 18 19]]
(5, 3)


In [19]:
#Checking for null values
df.isnull().sum()

Column1    0
Column2    0
Column3    0
Column4    0
dtype: int64

In [20]:
#Finding no. of different categorical features
df['Column1'].value_counts()

12    1
4     1
16    1
8     1
0     1
Name: Column1, dtype: int64

In [21]:
#To show unique values
df['Column1'].unique()

array([ 0,  4,  8, 12, 16])

In [22]:
print(df['Column1'])
print(type(df['Column1']))

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Column1, dtype: int64
<class 'pandas.core.series.Series'>


In [24]:
print(df[['Column1','Column2']])
print(type(df[['Column1','Column2']]))

      Column1  Column2
Row1        0        1
Row2        4        5
Row3        8        9
Row4       12       13
Row5       16       17
<class 'pandas.core.frame.DataFrame'>


In [2]:
#Comma Separated Values
#Change sep parameter to read other than comma separated
df = pd.read_csv('mercedesbenz.csv')

In [3]:
df.head()

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   
2   3  az  v  as  f  d  a  j  j    0  ...     0     0     0     1     0     0   
3   4  az  l   n  f  d  z  l  n    0  ...     0     0     0     1     0     0   
4   5   w  s  as  c  d  y  i  m    0  ...     1     0     0     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  
2     0     0     0     0  
3     0     0     0     0  
4     0     0     0     0  

[5 rows x 377 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Columns: 377 entries, ID to X385
dtypes: int64(369), object(8)
memory usage: 12.1+ MB


In [6]:
#Only int or float are considered here not objects
df.describe()

ID          X10          X11          X12          X13  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean   4211.039202     0.019007     0.000238     0.074364     0.061060   
std    2423.078926     0.136565     0.015414     0.262394     0.239468   
min       1.000000     0.000000     0.000000     0.000000     0.000000   
25%    2115.000000     0.000000     0.000000     0.000000     0.000000   
50%    4202.000000     0.000000     0.000000     0.000000     0.000000   
75%    6310.000000     0.000000     0.000000     0.000000     0.000000   
max    8416.000000     1.000000     1.000000     1.000000     1.000000   

               X14          X15          X16          X17          X18  ...  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  ...   
mean      0.427893     0.000713     0.002613     0.008791     0.010216  ...   
std       0.494832     0.026691     0.051061     0.093357     0.100570  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
50%       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
75%       1.000000     0.000000     0.000000     0.000000     0.000000  ...   
max       1.000000     1.000000     1.000000     1.000000     1.000000  ...   

              X375         X376         X377         X378         X379  \
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000   
mean      0.325968     0.049656     0.311951     0.019244     0.011879   
std       0.468791     0.217258     0.463345     0.137399     0.108356   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     0.000000     0.000000     0.000000     0.000000   
50%       0.000000     0.000000     0.000000     0.000000     0.000000   
75%       1.000000     0.000000     1.000000     0.000000     0.000000   
max       1.000000     1.000000     1.000000     1.000000     1.000000   

              X380         X382         X383         X384         X385  
count  4209.000000  4209.000000  4209.000000  4209.000000  4209.000000  
mean      0.008078     0.008791     0.000475     0.000713     0.001663  
std       0.089524     0.093357     0.021796     0.026691     0.040752  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     0.000000     0.000000     0.000000  
max       1.000000     1.000000     1.000000     1.000000     1.000000  

[8 rows x 369 columns]

In [8]:
df['X0'].value_counts()

ak    432
y     348
z     335
x     302
ay    299
t     293
o     246
f     213
w     198
j     171
n     167
aj    162
az    161
s     116
ap    108
al     88
h      64
d      61
e      48
v      40
ai     38
m      34
af     34
am     28
i      25
at     21
u      20
ba     19
a      18
b      13
ad     12
k      12
aw     11
aq     11
r      10
ax      8
l       6
bc      6
c       6
as      6
ao      5
au      5
g       3
ae      1
ag      1
p       1
av      1
an      1
bb      1
Name: X0, dtype: int64

In [11]:
df[df['X375']>0]

ID  X0  X1  X2 X3 X4  X5 X6 X8  X10  ...  X375  X376  X377  X378  \
4        5   w   s  as  c  d   y  i  m    0  ...     1     0     0     0   
5        8   y  aa  ai  e  d   x  g  s    0  ...     1     0     0     0   
13      19   o   v  ae  g  d   g  g  j    0  ...     1     0     0     0   
22      35   z   v  ai  e  d   f  j  m    0  ...     1     0     0     0   
26      45  ay  aa   m  c  d   j  g  t    0  ...     1     0     0     0   
...    ...  ..  ..  .. .. ..  .. .. ..  ...  ...   ...   ...   ...   ...   
4191  8386   s  aa  ai  c  d  aa  j  w    0  ...     1     0     0     0   
4192  8388  ay  aa  as  c  d  aa  l  o    0  ...     1     0     0     0   
4193  8389   f   p  ak  c  d  aa  j  h    0  ...     1     0     0     0   
4195  8394   z   v   a  b  d  aa  j  b    0  ...     1     0     0     0   
4208  8416   t  aa  ai  c  d  aa  g  r    0  ...     1     0     0     0   

      X379  X380  X382  X383  X384  X385  
4        0     0     0     0     0     0  
5        0     0     0     0     0     0  
13       0     0     0     0     0     0  
22       0     0     0     0     0     0  
26       0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...  
4191     0     0     0     0     0     0  
4192     0     0     0     0     0     0  
4193     0     0     0     0     0     0  
4195     0     0     0     0     0     0  
4208     0     0     0     0     0     0  

[1372 rows x 377 columns]

In [12]:
#Use a string as in memory buffer
from io import StringIO
StringIO()

In [16]:
#Specific column form csv file
df = pd.read_csv('mercedesbenz.csv',usecols = lambda x: x.upper() in ['X0','X1','X2'])

In [17]:
df.head()

X0 X1  X2
0  az  v   n
1   t  b  ai
2  az  v  as
3  az  l   n
4   w  s  as

In [18]:
data = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11')
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11


In [20]:
#Importing as a particular datatype
#All numbers are basically strings
df = pd.read_csv(StringIO(data),dtype=object)
df

a   b   c    d
0  1   2   3    4
1  5   6   7    8
2  9  10  11  NaN

In [21]:
df['a'][1]

'5'

In [31]:
data = ('a,b,c,d\n'
       '1,2,3,4\n'
       '5,6,7,8\n'
       '9,10,11,12')

In [23]:
df = pd.read_csv(StringIO(data),dtype=int)
df

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [24]:
df['a']

0    1
1    5
2    9
Name: a, dtype: int64

In [35]:
#Importing different columns with different data types
df = pd.read_csv(StringIO(data),dtype={'b':int, 'c':float, 'a':'Int64'})
df

a   b     c   d
0  1   2   3.0   4
1  5   6   7.0   8
2  9  10  11.0  12

In [36]:
df['a'][1]

5

In [37]:
#Checking the datatypes
df.dtypes

a      Int64
b      int64
c    float64
d      int64
dtype: object

In [38]:
data = ('index,a,b,c\n'
       '4,apple,bat,5.7\n'
       '8,orange,cow,10')


In [41]:
pd.read_csv(StringIO(data))

index       a    b     c
0      4   apple  bat   5.7
1      8  orange  cow  10.0

In [42]:
#Make 0th column as index
pd.read_csv(StringIO(data),index_col=0)

a    b     c
index                   
4       apple  bat   5.7
8      orange  cow  10.0

In [47]:
data = ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')
pd.read_csv(StringIO(data))

a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [49]:
#In this case 4 and 8 were not index
pd.read_csv(StringIO(data),index_col=False)

a       b    c
0  4   apple  bat
1  8  orange  cow

In [51]:
#Combine usecols and Index_col
data = ('a,b,c\n'
       '4,apple,bat,\n'
       '8,orange,cow,')
pd.read_csv(StringIO(data),usecols=['b','c'],index_col=False)

b    c
0   apple  bat
1  orange  cow

In [52]:
#Quoting and escape characters used in NLP
data = 'a,b\n"hello, \\"Bob\\", nice to see you",5'

In [53]:
pd.read_csv(StringIO(data),escapechar='\\')

a  b
0  hello, "Bob", nice to see you  5

In [54]:
#URL to CSV
#Note the different separator
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item',
                 sep='\t')

In [55]:
df.head()

item_code                                          item_name  display_level  \
0       AA0                               All items - old base              0   
1      AA0R  Purchasing power of the consumer dollar - old ...              0   
2       SA0                                          All items              0   
3      SA0E                                             Energy              1   
4     SA0L1                                All items less food              1   

  selectable  sort_sequence  
0          T              2  
1          T            399  
2          T              1  
3          T            374  
4          T            358

In [61]:
#Reading JSON
#JSON is like dictionaries
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df1 = pd.read_json(Data)
df1.head()

employee_name            email  \
0         James  james@gmail.com   

                                         job_profile  
0  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

In [57]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data',
                header=None)
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [58]:
#JSON to CSV
df.to_csv('wine.csv')

In [62]:
#JSON to different JSON formats
df1.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [63]:
#So use orient with a parameter like records
#This is important as it is used in frontend
df1.to_json(orient="records")

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [64]:
#Reading HTML content (having table tags)
url = 'https://www.fdic.gov/bank/individual/failed/banklist.html'
df = pd.read_html(url)

In [65]:
#It returns a list of tables
#Here first (0 index) is our required table
df[0]

Bank Name           City  ST   CERT  \
0                 The First State Bank  Barboursville  WV  14361   
1                   Ericson State Bank        Ericson  NE  18265   
2     City National Bank of New Jersey         Newark  NJ  21111   
3                        Resolute Bank         Maumee  OH  58317   
4                Louisa Community Bank         Louisa  KY  58112   
..                                 ...            ...  ..    ...   
556                 Superior Bank, FSB       Hinsdale  IL  32646   
557                Malta National Bank          Malta  OH   6629   
558    First Alliance Bank & Trust Co.     Manchester  NH  34264   
559  National State Bank of Metropolis     Metropolis  IL   3815   
560                   Bank of Honolulu       Honolulu  HI  21029   

                   Acquiring Institution       Closing Date  
0                         MVB Bank, Inc.      April 3, 2020  
1             Farmers and Merchants Bank  February 14, 2020  
2                        Industrial Bank   November 1, 2019  
3                     Buckeye State Bank   October 25, 2019  
4      Kentucky Farmers Bank Corporation   October 25, 2019  
..                                   ...                ...  
556                Superior Federal, FSB      July 27, 2001  
557                    North Valley Bank        May 3, 2001  
558  Southern New Hampshire Bank & Trust   February 2, 2001  
559              Banterra Bank of Marion  December 14, 2000  
560                   Bank of the Orient   October 13, 2000  

[561 rows x 6 columns]

In [76]:
#Table of mcc(mobile country codes) from wikipedia
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
#This page has multiple tables, it picks up the one having country column
#header
#A list of datafrmaes is commonly called as dfs
dfs = pd.read_html(url_mcc, match='country', header=0)

In [77]:
dfs[0]

Mobile country code                                    Country ISO 3166  \
0                    289                                 A Abkhazia    GE-AB   
1                    412                                Afghanistan       AF   
2                    276                                    Albania       AL   
3                    603                                    Algeria       DZ   
4                    544  American Samoa (United States of America)       AS   
..                   ...                                        ...      ...   
247                  452                                    Vietnam       VN   
248                  543                        W Wallis and Futuna       WF   
249                  421                                    Y Yemen       YE   
250                  645                                   Z Zambia       ZM   
251                  648                                   Zimbabwe       ZW   

                                  Mobile network codes National MNC authority  \
0             List of mobile network codes in Abkhazia                    NaN   
1          List of mobile network codes in Afghanistan                    NaN   
2              List of mobile network codes in Albania                    NaN   
3              List of mobile network codes in Algeria                    NaN   
4       List of mobile network codes in American Samoa                    NaN   
..                                                 ...                    ...   
247        List of mobile network codes in the Vietnam                    NaN   
248  List of mobile network codes in Wallis and Futuna                    NaN   
249          List of mobile network codes in the Yemen                    NaN   
250             List of mobile network codes in Zambia                    NaN   
251           List of mobile network codes in Zimbabwe                    NaN   

                      Remarks  
0    MCC is not listed by ITU  
1                         NaN  
2                         NaN  
3                         NaN  
4                         NaN  
..                        ...  
247                       NaN  
248                       NaN  
249                       NaN  
250                       NaN  
251                       NaN  

[252 rows x 6 columns]

In [79]:
#Reading excel file
df_excel = pd.read_excel('SampleData.xlsx')
df_excel.head()

Unnamed: 0 Unnamed: 1               Unnamed: 2
0         NaN        NaN                      NaN
1         NaN        NaN                      NaN
2         NaN        NaN                      NaN
3         NaN        NaN  Online Instruction Page
4         NaN        NaN    Sample Data for Excel

In [82]:
#Pickling
#Used to save data structure to disk using pickle format
#All pandas object support it
dfs[0].to_pickle('saved_df')
df = pd.read_pickle('saved_df')
df.head()

Mobile country code                                    Country ISO 3166  \
0                  289                                 A Abkhazia    GE-AB   
1                  412                                Afghanistan       AF   
2                  276                                    Albania       AL   
3                  603                                    Algeria       DZ   
4                  544  American Samoa (United States of America)       AS   

                             Mobile network codes National MNC authority  \
0        List of mobile network codes in Abkhazia                    NaN   
1     List of mobile network codes in Afghanistan                    NaN   
2         List of mobile network codes in Albania                    NaN   
3         List of mobile network codes in Algeria                    NaN   
4  List of mobile network codes in American Samoa                    NaN   

                    Remarks  
0  MCC is not listed by ITU  
1                       NaN  
2                       NaN  
3                       NaN  
4                       NaN